In [7]:
import numpy as np

In [8]:
x = np.arange(10)

In [12]:
x**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
x.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [32]:
sqrd = np.vectorize(lambda x: x**2)

In [33]:
sqrd(x)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
def piArray(n):
    series = 4.*np.arange(1,n+1)**2
    series /= (series-1)
    print(series.prod()*2)

In [29]:
%timeit piArray(1000000)

3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.14159186819
3.1415

TypeError: unsupported operand type(s) for @: 'numpy.ndarray' and 'numpy.ndarray'